config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "lists#index"

  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @list = List.find(params[:list_id])
    @movies = Movie.all
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to lists_path
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end
  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    p Bookmark.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end
  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Submit bookmark", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container p-3">
  <%= link_to "Create a new list!", new_list_url, class: "btn btn-primary"%>
  <div class="row">
    <% @lists.each do |item| %>
    <div class="card m-3 d-flex flex-column justify-content-between" style="width: 25rem;">
      <% if item.photo.key != nil %>
        <%= cl_image_tag item.photo.key, crop: :fill, class: "card-img-top", style: "height: 300px"  %>
      <% else %>
        <%= image_tag "WROND.png", class: "card-img-top", style: "height: 300px" %>
      <% end %>
      <div class="card-body d-flex justify-content-between", style="height: fit-content">
        <h5 class="card-title"><%=item.name%></h5>
        <div>
          <%= link_to "Details", list_url(item), class: "btn btn-primary"%>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
I'm creating something new

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Create a list!", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<div class="container p-3">
  <h1 class="text-center m-6"><%= @list.name %></h1>
  <% if @list.photo.key != nil %>
    <%= cl_image_tag @list.photo.key, crop: :fill, class: "card-img-top", style: "height: 300px"  %>
  <% else %>
    <%= image_tag "WROND.png", class: "card-img-top", style: "height: 300px, width: auto" %>
  <% end %>
  <p><strong>Bookmarks, I guess</strong></p>
  <ul class="list-group py-3">
    <% @list.bookmarks.each do |mark| %>
      <li class="list-group-item"><%= mark.movie.title %> - <%= mark.comment %> <%= link_to 'Delete', mark, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}%></li>
    <% end %>
  </ul>
  <%= link_to "Add a new bookmark", new_list_bookmark_url(@list), class: "btn btn-primary"%>
  <%= link_to "Back to lists", lists_url, class: "btn btn-primary"%>
  <%= link_to 'Delete this list', @list, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger"%>
</div>